### ISSUE TITLE
HMI must put applications to HMI level "LIMITED"

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_hmi#101]
**Bug Report**
HMI must put applications to HMI level "LIMITED"

**Precondition**:
1. SDL and HMI are started.
3. Mobile app is registered and activated,  HMI level = FULL or BACKGROUND

**Steps**:
Go to menu Apps.

**Expected Behavior**:
HMI level of application becomes LIMITED

**Observed Behavior**:
HMI level of application still FULL or BACKGROUND

**Comment by LitvinenkoIra** [comment]
observed this issue with the following steps: 

1.    SDL and HMI are started.
2.    Mobile app is registered and activated, HMI level = FULL
3.    Go to menu with settings 

**Expected Behavior:**
HMI level of application becomes LIMITED

**Observed Behavior:**
HMI level of application still FULL 

HMI: https://github.com/smartdevicelink/sdl_hmi/tree/develop
commit: 40ad9f312ba5418117fc7ce91a33dfb6cda97bdf

**Comment by ValeriiMalkov** [comment]
Fixed in the [Pull request](https://github.com/smartdevicelink/sdl_hmi/pull/110)

**Comment by jacobkeeler** [comment]
Closing with the merge of #538
