### ISSUE TITLE
TurnList items appear on top of one another

### ISSUE THREAD

**Issue by RHenigan** [smartdevicelink/sdl_hmi#483]
When creating a Turn list, the list presented shows all items in the same location rather than listing the items. The below image is of a list containing items with the following text ("turn 1", "turn 2", "turn 3")

<img width="977" alt="Screen Shot 2021-02-08 at 10 18 45 AM" src="https://user-images.githubusercontent.com/19917852/107241493-06fdc680-69f9-11eb-9f4c-62531b0293e3.png">

**Comment by GetmanetsIrina** [comment]
**Precondition:**
1. `Navigation-1` group is assigned to mobile app
2. SDL and HMI are started
3. Navigation app is registered and activated
4. `ShowConstantTBT` is requested successfully

**Steps to reproduce:**
1. Mobile app requests `UpdateTurnList` with turn items without images

**Expected result:**
1. HMI responds with SUCCESS to `Navigation.UpdateTurnList`
2. HMI shows the list of added turn items in `Turn List`

**Observed behavior:**
HMI shows all turn items in the same location rather than listing the items in `Turn List`

**Comment by Ypostolov** [comment]
@jordynmackool PR with fix is ready for Livio review. Thank you.

**Comment by jordynmackool** [comment]
@Ypostolov Thanks for letting us know the PR is ready for Livio review. We are currently in a code freeze as development for the upcoming October release is complete. We will plan to review this PR when time allows. Thanks!
