### ISSUE TITLE
EndTime is not displayed when SetMediaClock set (UpdateMode=COUNTDOWN) with valid startTime and EndTime

### ISSUE THREAD

**Issue by VNikiforov-dev** [smartdevicelink/sdl_hmi#627]
**Description:**

EndTime is not displayed when SetMediaClock set (UpdateMode=COUNTDOWN) with valid startTime and endTime

**Precondition:**

1. Start SDL and HMI
2. App registered and activated

**Steps to reproduce:**

1. Send RPC from mobile
`SetMediaClock(Start Time = {hours=0, minutes=12, seconds=34}, EndTime =  {hours=0, minutes=11, seconds=34}, UpdateMode=COUNTDOWN, countRate = 1)`

**Expected result:**

1. StartTime and EndTime are displayed on HMI

**Actual result:**

1. StartTime is displayed on HMI, but **EndTime is not displayed** on HMI

![изображение](https://user-images.githubusercontent.com/79140692/136038750-2dfbcd37-ec86-4a2f-9f11-fb816e63f490.png)

Note: **Counter works!** Counter stops on 00:11:34
Start and EndTime displayed when SetMediaClock set count up 

![изображение](https://user-images.githubusercontent.com/79140692/136039394-3e337d8c-54db-4978-b1b7-5f42efad6262.png)

OS & Version Information

- OS/Version: [Ubuntu 18]
- SDL Core Version: [ https://github.com/smartdevicelink/sdl_core/tree/release/8.0.0 (5da5770 )]
- HMI: [https://github.com/smartdevicelink/sdl_hmi/tree/release/5.6.0 (ceb8b3c)]
- SPT: 20210729-Android

**Comment by VNikiforov-dev** [comment]
Please notice Luxoft team is going to prepare a fix.

**Comment by jacobkeeler** [comment]
@VNikiforov-dev This behavior is intentional, though if you are able to display the endTime in a way that isn't confusing, I'm fine with attempting to change this behavior.

Admittedly, sending `COUNTDOWN` with an `endTime` is a bit of an unrealistic case from what I can tell, so the expected behavior is a bit unclear.

**Comment by VNikiforov-dev** [comment]
@jacobkeeler I would propose to display startTime on first position with minus sign and endTime on second position.
Like:
-00:13:22 / 00:12:35
-00:13:21 / 00:12:35
-00:13:20 / 00:12:35

**Comment by VNikiforov-dev** [comment]
@jacobkeeler Is it ok with you?

**Comment by jacobkeeler** [comment]
Hmm, I still don't think that approach is very clear either. Perhaps it would be better to have an extra countdown which indicates when it will stop using the difference between startTime and endTime? Something like:

00:13:22 (-00:00:47)
00:13:21 (-00:00:46)
00:13:20 (-00:00:45)
...
00:12:35 (-00:00:00)

**Comment by jacobkeeler** [comment]
Even then, I'm still not certain that this is really an issue that needs to be solved, as I really can't see a use case for stopping a timer countdown partway through (besides sending a PAUSE event). It would make more sense to me if endTime was larger than startTime for the purpose of calculating the progress bar (endTime would mark the end of the progress bar and startTime would mark the current position in the countdown), but with how the validation in Core works as of now, this wouldn't be possible.

**Comment by GetmanetsIrina** [comment]
@jacobkeeler, the Luxotf team is okay with your solution described in https://github.com/smartdevicelink/sdl_hmi/issues/627#issuecomment-962200677 .

But I want to ask due to your note `Even then, I'm still not certain that this is really an issue that needs to be solved` - Are you okay that the Luxoft team is going to fix this issue?

**Comment by GetmanetsIrina** [comment]
@jacobkeeler, a gentle reminder about the current discussion.

**Comment by jacobkeeler** [comment]
@GetmanetsIrina apologies, I've been on other projects the past few weeks. After thinking on it a bit more, I think that I'd be fine if we implemented the solution mentioned in https://github.com/smartdevicelink/sdl_hmi/issues/627#issuecomment-962200677, with the following addition:

- If `endTime` is set to `00:00:00`, then we still omit this from the timer (since that endTime is implied by the countdown timer)
