### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by dboltovskyi** [smartdevicelink/sdl_hmi#640]
Uncaught TypeError: Cannot read properties of null (reading 'hasOwnProperty') on 'DELETE' button

**Precondition:**
1. Initial pre-conditions for WebEngine Projection mode are executed
2. SDL and HMI are started
3. Web app (hello-webengine3) is registered

**Steps to reproduce:**
Web app requests Show ("templateTitle":"DEFAULT","templateConfiguration":{"template":"DEFAULT"}})

**Expected result:**
HMI displays the WEB_VIEW template

**Actual result:**
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'name')
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'name')
 at t.value (RpcStruct.js:135)
 at t.value (DisplayCapabilities.js:105)
 at n.value (SystemCapabilityManager.js:708)
 at n.value (SystemCapabilityManager.js:691)
 at n.value (SystemCapabilityManager.js:674)
 at e (SystemCapabilityManager.js:600)
 at _LifecycleManager.js:160
 at Array.forEach (<anonymous>)
 at n.value (_LifecycleManager.js:159)
 at e._onRpcMessageReceived (_LifecycleManager.js:125)
```

**OS & Version Information:**
- OS/Version: Ubuntu 18.04
- SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/8.0.0-RC1 (86e032f)
- HMI: https://github.com/smartdevicelink/sdl_hmi/tree/release/5.6.0 (4d7c0b5)
- SPT: 20210729-Android

**Comment by theresalech** [comment]
Hi @dboltovskyi , thanks for letting us know. Please advise once the fix is ready for our review, and note that the initial Steering Committee review period for this release ends today (2021-10-14), so we'll need the fix as soon as possible to ensure its inclusion in SDL HMI 5.6.

**Comment by AKalinich-Luxoft** [comment]
@theresalech
Let me explain the situation here. The described issue is happening inside of web applications that are not the part of `sdl_hmi` repository, so no changes are required for this repository. The web applications are based on top of the `sdl_javascript_suite` library and the failure is happening inside the library itself. Luckily, this issue has been already [reported](https://github.com/smartdevicelink/sdl_javascript_suite/issues/389) and [fixed](https://github.com/smartdevicelink/sdl_javascript_suite/pull/390) in the new version of the JS library. However, existing web applications are using the outdated version of the `sdl_javascript_suite` without that fix so the issue is still observed.
Summarizing above, in order to resolve that issue, we have to update the file `SDL.min.js` for each existing web application supplied by [AWS service](https://sdl-webengine-app-store-example.s3.amazonaws.com/app-directory.json). These applications are stored at `https://sdl-webengine-app-store-example.s3.amazonaws.com` and unfortunately, only the Livio team has access there. So only the Livio team can actually resolve that issue.
Once all web applications were updated, this issue won't be reproducible and can be closed.
Is it possible to assign somebody from the Livio team to do that?

**Comment by AKalinich-Luxoft** [comment]
@theresalech 
Luxoft team can support that if you have any additional questions regarding what should be done
